### PR TITLE
Add flatpak support for linux

### PR DESCRIPTION
**Pull request by CoffeeIsLife87**
I needed support for flatpak support so I added it
Lemme know if there are any changes you'd like me to make

### CODE REVIEW

**Comment by LovecraftianHorror** [comment]
I'll take a look tomorrow!

**Review by LovecraftianHorror — APPROVED** [review]
Setup flatpak and installed Steam along with a couple of games. Everything seems to work so it gets a LGTM!

Congratz on your first PR to this repo :tada:

**Comment by LovecraftianHorror** [comment]
I'll leave this up to @WilliamVenner for the final say, but it gets a :+1: from me

**Comment by WilliamVenner** [comment]
Thank you!

**Comment by GeckoEidechse** [comment]
Any chance the [crate on crates.io](https://crates.io/crates/steamlocate) could be updated to include this change? ^^

Using the version `1.0.1` on crates.io, `steamlocate::SteamDir::locate()` is unable to find my Flatpak Steam install but using the most recent commit from this repo, the Flatpak Steam install is successfully found :D

**Comment by WilliamVenner** [comment]
published as 1.0.2 :) @GeckoEidechse

**Comment by GeckoEidechse** [comment]
Confirmed working, many thanks <3

**Pull request merged**
